spring.profiles.active: top

hr.payRaise:
  defaultConfig:
    percent:
      baseValue: 5
  smartConfig:
    limit:
      highValue: 10.0
      middleValue: 5.0
      lowValue: 2.5
    percent:
      highValue: 10
      middleValue: 5
      lowValue: 2
      baseValue: 0
  advancedConfig:
    limit:
      arbitraryValues:
      - 10.0
      - 5.0
      - 2.5
    percent:
      arbitraryValues:
      - 15
      - 10
      - 5
      - 0
  topConfig:
    percentsToLimits:
      10.0: 20
      5.0: 15
      2.5: 10
      0.0: 5